# Generated by Django 4.1.7 on 2023-04-20 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='Cliente_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='marca_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.marca', verbose_name='Fabricante'),
        ),
    ]
